dotnet-challenge/Models/AppDBContext.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using dotnet_challenge.Models;
namespace dotnet_challenge.Models
{
    public class DotNetChallengeContext : DbContext
    {
        public DotNetChallengeContext(DbContextOptions<DotNetChallengeContext> options)
            : base(options) { }

        public DbSet<User> Users { get; set; }
        public DbSet<Message> Messages { get; set; }
    }
}

dotnet-challenge/Models/Message.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace dotnet_challenge.Models
{
    public class Message
    {
        public int messageId { get; set; }
        public int userId { get; set; }
        public string content { get; set; }
        public String timeStamp { get; set; }
        public User user { get; set; } = new User();
    }
}

dotnet-challenge/Models/User.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
namespace dotnet_challenge.Models
{
    public class User
    {
        public int userId { get; set; }
        public string fullName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string type { get; set; } = "STANDARD";
        public List<Message> messages { get; set; }
    }
}

dotnet-challenge/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace dotnet_challenge.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

dotnet-challenge/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using dotnet_challenge.Models;
namespace dotnet_challenge.Pages
{
    public class IndexModel : PageModel
    {
        private readonly DotNetChallengeContext _context;
        public List<Message> messages;
        public IndexModel(DotNetChallengeContext context)
        {
            _context = context;
            messages = new List<Message>();
        }
        public string accessToken { get; set; } = "";
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("authorization") == null)
            {
                return RedirectToPage("/login");
            }
            accessToken = HttpContext.Session.GetString("authorization");
            if(!Utils.isValidJwt(accessToken, _context)){
                HttpContext.Session.SetString("authorization", "");
                return RedirectToPage("/login");
            }
            messages = (from m in _context.Messages
                        join u in _context.Users on m.userId equals u.userId
                        orderby m.timeStamp descending
                        select new Message
                        {
                            messageId = m.messageId,
                            content = m.content,
                            user = new User() { fullName = u.fullName }
                        }).Take(50).ToList();
            messages.Reverse();
            return new PageResult();
        }
    }
}

dotnet-challenge/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using dotnet_challenge.Models;
using Microsoft.AspNetCore.Http;
namespace dotnet_challenge.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class LoginModel : PageModel
    {
        private readonly DotNetChallengeContext _context;
        public LoginModel(DotNetChallengeContext context)
        {
            _context = context;
        }
        [BindProperty]
        public User signIn { get; set; }
        [BindProperty]
        public User signUp { get; set; }
        public string messageSingUp { get; set; } = String.Empty;
        public string messageSingIn { get; set; } = String.Empty;

        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostSignInAsync()
        {
            var user = _context.Users.Where(b => b.userName == signIn.userName && b.password == Utils.CreateMD5(signIn.password)).FirstOrDefault();
            if (user == null)
            {
                messageSingIn = "Invalid credentials";
                return Page();
            }
            messageSingIn = String.Empty;
            HttpContext.Session.SetString("authorization", Utils.Jwt(user.userName, user.password));
            return RedirectToPage("/index");
        }
        public async Task<IActionResult> OnPostSignUpAsync()
        {
            signUp.password = Utils.CreateMD5(signUp.password);
            _context.Users.Add(signUp);
            await _context.SaveChangesAsync();
            messageSingUp = "Successful registration";
            return Page();
        }
    }
}

dotnet-challenge/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace dotnet_challenge.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

dotnet-challenge/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="container">
    <div id="container-mesgs">
 
        @if (Model.messages.Count() == 0){
            <div id="empty-state">
                <h4>There are no Messages</h4>
            </div>
        }
        @foreach (var item in Model.messages)
        {
            <div class="mesg">
                <span>@item.user.fullName</span>
            <p>
                @item.content
            </p>
            </div>
        }
    </div>
    <div id="container-input" class="container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-6">
                <input type="text" id="mesgTextBox" class="form-control" placeholder="Enter message">
            </div>
            <div class="col col-lg-1">
                <button type="buton" id="sendButton" class="btn btn-primary">Send</button>
            </div>
        </div>
    </div>
</div>
<style>
    html, body, #container{
        height: 100%;
        margin: 0;
    }
    #container-mesgs{
        height: calc(100% - 50px);
        overflow-y: scroll;
    }
    .mesg{
        max-width: 500px;
        text-align: right;
        float: right;  
        clear: both; 
        padding-right: 25px;
    }
    .mesg span{
        font-size: 12px
    }
    #empty-state{
        display: flex;
        position: absolute;
        width: 100%;
        height: 100%;
        justify-content: center;
        align-items: center;
    }
 
</style>

<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>
<script>
    initializeSignalR("@Model.accessToken")
</script>

dotnet-challenge/Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-lg-4">
      <form method="POST">
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control"  asp-for="signIn.userName" placeholder="Enter username" required>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" asp-for="signIn.password" placeholder="Password" required>
        </div>
        <button type="submit" asp-page-handler="SignIn" class="btn btn-primary">Sign in</button>
        @Model.messageSingIn
      </form>
    </div>
    <div class="col col-lg-4">
      <form method="POST">
       <div class="form-group">
          <label for="exampleInputEmail1">Full name</label>
          <input type="text" class="form-control" asp-for="signUp.fullName" aria-describedby="emailHelp" placeholder="Enter Full Name" required>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control" asp-for="signUp.userName" aria-describedby="emailHelp" placeholder="Enter Username" required>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" asp-for="signUp.password" placeholder="Password" required>
        </div> 
        <button type="submit" asp-page-handler="SignUp" class="btn btn-primary">Sign up</button>
        
        @Model.messageSingUp
      </form>
    </div>
  </div>
</div>

dotnet-challenge/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnet_challenge</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
   @RenderBody()
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>